# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &wenjin age1swanwyhp3k6nycu2q3pyurgugzj4wlxg84gaj272rky0xu8j7ynq2eek7w
  - &wsl age12ayzjw7mlg778zuquvshy54p8q7af4ctw7tv979gr9m0cfehrs5sl7pt9d
creation_rules:
  - path_regex: ^secrets.yaml$
    key_groups:
    - age:
      - *wenjin
      - *wsl
